env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/jsx-runtime
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - off
    - 2
    - SwitchCase: 1
  '@typescript-eslint/indent':
    - off
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  '@typescript-eslint/no-non-null-assertion':
    - off
  '@typescript-eslint/no-unused-vars':
    - off
