// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Models/Indexer/Proto/Criteria.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tradie.Analyzer.Proto {

  /// <summary>Holder for reflection information generated from Models/Indexer/Proto/Criteria.proto</summary>
  public static partial class CriteriaReflection {

    #region Descriptor
    /// <summary>File descriptor for Models/Indexer/Proto/Criteria.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CriteriaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNNb2RlbHMvSW5kZXhlci9Qcm90by9Dcml0ZXJpYS5wcm90byK+AQoIQ3Jp",
            "dGVyaWESCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIbCgRraW5kGAMgASgO",
            "Mg0uQ3JpdGVyaWFLaW5kEhoKDG1vZGlmaWVySGFzaBgKIAEoA0ICMAFIABIQ",
            "CgZsZWFndWUYCyABKAlIABISCghjYXRlZ29yeRgMIAEoCUgAEhUKC3N1YmNh",
            "dGVnb3J5GA0gASgJSAASFAoKaXRlbVR5cGVJZBgOIAEoBUgAQgwKCnVuZGVy",
            "bHlpbmcqbwoMQ3JpdGVyaWFLaW5kEgsKB1VOS05PV04QABIMCghNT0RJRklF",
            "UhABEgoKBkxFQUdVRRACEgwKCENBVEVHT1JZEAMSDwoLU1VCQ0FURUdPUlkQ",
            "BBINCglJVEVNX1RZUEUQBRIKCgZVTklRVUUQBkIYqgIVVHJhZGllLkFuYWx5",
            "emVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tradie.Analyzer.Proto.CriteriaKind), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tradie.Analyzer.Proto.Criteria), global::Tradie.Analyzer.Proto.Criteria.Parser, new[]{ "Id", "Name", "Kind", "ModifierHash", "League", "Category", "Subcategory", "ItemTypeId" }, new[]{ "Underlying" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CriteriaKind {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("MODIFIER")] Modifier = 1,
    [pbr::OriginalName("LEAGUE")] League = 2,
    [pbr::OriginalName("CATEGORY")] Category = 3,
    [pbr::OriginalName("SUBCATEGORY")] Subcategory = 4,
    [pbr::OriginalName("ITEM_TYPE")] ItemType = 5,
    [pbr::OriginalName("UNIQUE")] Unique = 6,
  }

  #endregion

  #region Messages
  public sealed partial class Criteria : pb::IMessage<Criteria>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Criteria> _parser = new pb::MessageParser<Criteria>(() => new Criteria());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Criteria> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tradie.Analyzer.Proto.CriteriaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Criteria() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Criteria(Criteria other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      kind_ = other.kind_;
      switch (other.UnderlyingCase) {
        case UnderlyingOneofCase.ModifierHash:
          ModifierHash = other.ModifierHash;
          break;
        case UnderlyingOneofCase.League:
          League = other.League;
          break;
        case UnderlyingOneofCase.Category:
          Category = other.Category;
          break;
        case UnderlyingOneofCase.Subcategory:
          Subcategory = other.Subcategory;
          break;
        case UnderlyingOneofCase.ItemTypeId:
          ItemTypeId = other.ItemTypeId;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Criteria Clone() {
      return new Criteria(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 3;
    private global::Tradie.Analyzer.Proto.CriteriaKind kind_ = global::Tradie.Analyzer.Proto.CriteriaKind.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tradie.Analyzer.Proto.CriteriaKind Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "modifierHash" field.</summary>
    public const int ModifierHashFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ModifierHash {
      get { return underlyingCase_ == UnderlyingOneofCase.ModifierHash ? (long) underlying_ : 0L; }
      set {
        underlying_ = value;
        underlyingCase_ = UnderlyingOneofCase.ModifierHash;
      }
    }

    /// <summary>Field number for the "league" field.</summary>
    public const int LeagueFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string League {
      get { return underlyingCase_ == UnderlyingOneofCase.League ? (string) underlying_ : ""; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        underlyingCase_ = UnderlyingOneofCase.League;
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Category {
      get { return underlyingCase_ == UnderlyingOneofCase.Category ? (string) underlying_ : ""; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        underlyingCase_ = UnderlyingOneofCase.Category;
      }
    }

    /// <summary>Field number for the "subcategory" field.</summary>
    public const int SubcategoryFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Subcategory {
      get { return underlyingCase_ == UnderlyingOneofCase.Subcategory ? (string) underlying_ : ""; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        underlyingCase_ = UnderlyingOneofCase.Subcategory;
      }
    }

    /// <summary>Field number for the "itemTypeId" field.</summary>
    public const int ItemTypeIdFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemTypeId {
      get { return underlyingCase_ == UnderlyingOneofCase.ItemTypeId ? (int) underlying_ : 0; }
      set {
        underlying_ = value;
        underlyingCase_ = UnderlyingOneofCase.ItemTypeId;
      }
    }

    private object underlying_;
    /// <summary>Enum of possible cases for the "underlying" oneof.</summary>
    public enum UnderlyingOneofCase {
      None = 0,
      ModifierHash = 10,
      League = 11,
      Category = 12,
      Subcategory = 13,
      ItemTypeId = 14,
    }
    private UnderlyingOneofCase underlyingCase_ = UnderlyingOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UnderlyingOneofCase UnderlyingCase {
      get { return underlyingCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUnderlying() {
      underlyingCase_ = UnderlyingOneofCase.None;
      underlying_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Criteria);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Criteria other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Kind != other.Kind) return false;
      if (ModifierHash != other.ModifierHash) return false;
      if (League != other.League) return false;
      if (Category != other.Category) return false;
      if (Subcategory != other.Subcategory) return false;
      if (ItemTypeId != other.ItemTypeId) return false;
      if (UnderlyingCase != other.UnderlyingCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) hash ^= Kind.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.ModifierHash) hash ^= ModifierHash.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.League) hash ^= League.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.Category) hash ^= Category.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.Subcategory) hash ^= Subcategory.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.ItemTypeId) hash ^= ItemTypeId.GetHashCode();
      hash ^= (int) underlyingCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Kind);
      }
      if (underlyingCase_ == UnderlyingOneofCase.ModifierHash) {
        output.WriteRawTag(80);
        output.WriteInt64(ModifierHash);
      }
      if (underlyingCase_ == UnderlyingOneofCase.League) {
        output.WriteRawTag(90);
        output.WriteString(League);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Category) {
        output.WriteRawTag(98);
        output.WriteString(Category);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Subcategory) {
        output.WriteRawTag(106);
        output.WriteString(Subcategory);
      }
      if (underlyingCase_ == UnderlyingOneofCase.ItemTypeId) {
        output.WriteRawTag(112);
        output.WriteInt32(ItemTypeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Kind);
      }
      if (underlyingCase_ == UnderlyingOneofCase.ModifierHash) {
        output.WriteRawTag(80);
        output.WriteInt64(ModifierHash);
      }
      if (underlyingCase_ == UnderlyingOneofCase.League) {
        output.WriteRawTag(90);
        output.WriteString(League);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Category) {
        output.WriteRawTag(98);
        output.WriteString(Category);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Subcategory) {
        output.WriteRawTag(106);
        output.WriteString(Subcategory);
      }
      if (underlyingCase_ == UnderlyingOneofCase.ItemTypeId) {
        output.WriteRawTag(112);
        output.WriteInt32(ItemTypeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (underlyingCase_ == UnderlyingOneofCase.ModifierHash) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ModifierHash);
      }
      if (underlyingCase_ == UnderlyingOneofCase.League) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(League);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Category) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Category);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Subcategory) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Subcategory);
      }
      if (underlyingCase_ == UnderlyingOneofCase.ItemTypeId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemTypeId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Criteria other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) {
        Kind = other.Kind;
      }
      switch (other.UnderlyingCase) {
        case UnderlyingOneofCase.ModifierHash:
          ModifierHash = other.ModifierHash;
          break;
        case UnderlyingOneofCase.League:
          League = other.League;
          break;
        case UnderlyingOneofCase.Category:
          Category = other.Category;
          break;
        case UnderlyingOneofCase.Subcategory:
          Subcategory = other.Subcategory;
          break;
        case UnderlyingOneofCase.ItemTypeId:
          ItemTypeId = other.ItemTypeId;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Kind = (global::Tradie.Analyzer.Proto.CriteriaKind) input.ReadEnum();
            break;
          }
          case 80: {
            ModifierHash = input.ReadInt64();
            break;
          }
          case 90: {
            League = input.ReadString();
            break;
          }
          case 98: {
            Category = input.ReadString();
            break;
          }
          case 106: {
            Subcategory = input.ReadString();
            break;
          }
          case 112: {
            ItemTypeId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Kind = (global::Tradie.Analyzer.Proto.CriteriaKind) input.ReadEnum();
            break;
          }
          case 80: {
            ModifierHash = input.ReadInt64();
            break;
          }
          case 90: {
            League = input.ReadString();
            break;
          }
          case 98: {
            Category = input.ReadString();
            break;
          }
          case 106: {
            Subcategory = input.ReadString();
            break;
          }
          case 112: {
            ItemTypeId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
