// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Models/Indexer/Proto/Criteria.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tradie.Analyzer.Proto {

  /// <summary>Holder for reflection information generated from Models/Indexer/Proto/Criteria.proto</summary>
  public static partial class CriteriaReflection {

    #region Descriptor
    /// <summary>File descriptor for Models/Indexer/Proto/Criteria.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CriteriaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNNb2RlbHMvSW5kZXhlci9Qcm90by9Dcml0ZXJpYS5wcm90bxokTW9kZWxz",
            "L0FuYWx5emVyL1Byb3RvL01vZGlmaWVyLnByb3RvGiJNb2RlbHMvQW5hbHl6",
            "ZXIvUHJvdG8vTGVhZ3VlLnByb3RvGiRNb2RlbHMvQW5hbHl6ZXIvUHJvdG8v",
            "SXRlbVR5cGUucHJvdG8i0wEKCENyaXRlcmlhEgoKAmlkGAEgASgJEgwKBG5h",
            "bWUYAiABKAkSGwoEa2luZBgDIAEoDjINLkNyaXRlcmlhS2luZBIdCghtb2Rp",
            "ZmllchgKIAEoCzIJLk1vZGlmaWVySAASGQoGbGVhZ3VlGAsgASgLMgcuTGVh",
            "Z3VlSAASEgoIY2F0ZWdvcnkYDCABKAlIABIVCgtzdWJjYXRlZ29yeRgNIAEo",
            "CUgAEh0KCGl0ZW1UeXBlGA4gASgLMgkuSXRlbVR5cGVIAEIMCgp1bmRlcmx5",
            "aW5nKm8KDENyaXRlcmlhS2luZBILCgdVTktOT1dOEAASDAoITU9ESUZJRVIQ",
            "ARIKCgZMRUFHVUUQAhIMCghDQVRFR09SWRADEg8KC1NVQkNBVEVHT1JZEAQS",
            "DQoJSVRFTV9UWVBFEAUSCgoGVU5JUVVFEAZCGKoCFVRyYWRpZS5BbmFseXpl",
            "ci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tradie.Analyzer.Proto.ModifierReflection.Descriptor, global::Tradie.Analyzer.Proto.LeagueReflection.Descriptor, global::Tradie.Analyzer.Proto.ItemTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tradie.Analyzer.Proto.CriteriaKind), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tradie.Analyzer.Proto.Criteria), global::Tradie.Analyzer.Proto.Criteria.Parser, new[]{ "Id", "Name", "Kind", "Modifier", "League", "Category", "Subcategory", "ItemType" }, new[]{ "Underlying" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CriteriaKind {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("MODIFIER")] Modifier = 1,
    [pbr::OriginalName("LEAGUE")] League = 2,
    [pbr::OriginalName("CATEGORY")] Category = 3,
    [pbr::OriginalName("SUBCATEGORY")] Subcategory = 4,
    [pbr::OriginalName("ITEM_TYPE")] ItemType = 5,
    [pbr::OriginalName("UNIQUE")] Unique = 6,
  }

  #endregion

  #region Messages
  public sealed partial class Criteria : pb::IMessage<Criteria>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Criteria> _parser = new pb::MessageParser<Criteria>(() => new Criteria());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Criteria> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tradie.Analyzer.Proto.CriteriaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Criteria() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Criteria(Criteria other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      kind_ = other.kind_;
      switch (other.UnderlyingCase) {
        case UnderlyingOneofCase.Modifier:
          Modifier = other.Modifier.Clone();
          break;
        case UnderlyingOneofCase.League:
          League = other.League.Clone();
          break;
        case UnderlyingOneofCase.Category:
          Category = other.Category;
          break;
        case UnderlyingOneofCase.Subcategory:
          Subcategory = other.Subcategory;
          break;
        case UnderlyingOneofCase.ItemType:
          ItemType = other.ItemType.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Criteria Clone() {
      return new Criteria(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 3;
    private global::Tradie.Analyzer.Proto.CriteriaKind kind_ = global::Tradie.Analyzer.Proto.CriteriaKind.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tradie.Analyzer.Proto.CriteriaKind Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "modifier" field.</summary>
    public const int ModifierFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tradie.Analyzer.Proto.Modifier Modifier {
      get { return underlyingCase_ == UnderlyingOneofCase.Modifier ? (global::Tradie.Analyzer.Proto.Modifier) underlying_ : null; }
      set {
        underlying_ = value;
        underlyingCase_ = value == null ? UnderlyingOneofCase.None : UnderlyingOneofCase.Modifier;
      }
    }

    /// <summary>Field number for the "league" field.</summary>
    public const int LeagueFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tradie.Analyzer.Proto.League League {
      get { return underlyingCase_ == UnderlyingOneofCase.League ? (global::Tradie.Analyzer.Proto.League) underlying_ : null; }
      set {
        underlying_ = value;
        underlyingCase_ = value == null ? UnderlyingOneofCase.None : UnderlyingOneofCase.League;
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Category {
      get { return underlyingCase_ == UnderlyingOneofCase.Category ? (string) underlying_ : ""; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        underlyingCase_ = UnderlyingOneofCase.Category;
      }
    }

    /// <summary>Field number for the "subcategory" field.</summary>
    public const int SubcategoryFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Subcategory {
      get { return underlyingCase_ == UnderlyingOneofCase.Subcategory ? (string) underlying_ : ""; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        underlyingCase_ = UnderlyingOneofCase.Subcategory;
      }
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tradie.Analyzer.Proto.ItemType ItemType {
      get { return underlyingCase_ == UnderlyingOneofCase.ItemType ? (global::Tradie.Analyzer.Proto.ItemType) underlying_ : null; }
      set {
        underlying_ = value;
        underlyingCase_ = value == null ? UnderlyingOneofCase.None : UnderlyingOneofCase.ItemType;
      }
    }

    private object underlying_;
    /// <summary>Enum of possible cases for the "underlying" oneof.</summary>
    public enum UnderlyingOneofCase {
      None = 0,
      Modifier = 10,
      League = 11,
      Category = 12,
      Subcategory = 13,
      ItemType = 14,
    }
    private UnderlyingOneofCase underlyingCase_ = UnderlyingOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UnderlyingOneofCase UnderlyingCase {
      get { return underlyingCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUnderlying() {
      underlyingCase_ = UnderlyingOneofCase.None;
      underlying_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Criteria);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Criteria other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Kind != other.Kind) return false;
      if (!object.Equals(Modifier, other.Modifier)) return false;
      if (!object.Equals(League, other.League)) return false;
      if (Category != other.Category) return false;
      if (Subcategory != other.Subcategory) return false;
      if (!object.Equals(ItemType, other.ItemType)) return false;
      if (UnderlyingCase != other.UnderlyingCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) hash ^= Kind.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.Modifier) hash ^= Modifier.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.League) hash ^= League.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.Category) hash ^= Category.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.Subcategory) hash ^= Subcategory.GetHashCode();
      if (underlyingCase_ == UnderlyingOneofCase.ItemType) hash ^= ItemType.GetHashCode();
      hash ^= (int) underlyingCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Kind);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Modifier) {
        output.WriteRawTag(82);
        output.WriteMessage(Modifier);
      }
      if (underlyingCase_ == UnderlyingOneofCase.League) {
        output.WriteRawTag(90);
        output.WriteMessage(League);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Category) {
        output.WriteRawTag(98);
        output.WriteString(Category);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Subcategory) {
        output.WriteRawTag(106);
        output.WriteString(Subcategory);
      }
      if (underlyingCase_ == UnderlyingOneofCase.ItemType) {
        output.WriteRawTag(114);
        output.WriteMessage(ItemType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Kind);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Modifier) {
        output.WriteRawTag(82);
        output.WriteMessage(Modifier);
      }
      if (underlyingCase_ == UnderlyingOneofCase.League) {
        output.WriteRawTag(90);
        output.WriteMessage(League);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Category) {
        output.WriteRawTag(98);
        output.WriteString(Category);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Subcategory) {
        output.WriteRawTag(106);
        output.WriteString(Subcategory);
      }
      if (underlyingCase_ == UnderlyingOneofCase.ItemType) {
        output.WriteRawTag(114);
        output.WriteMessage(ItemType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Modifier) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Modifier);
      }
      if (underlyingCase_ == UnderlyingOneofCase.League) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(League);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Category) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Category);
      }
      if (underlyingCase_ == UnderlyingOneofCase.Subcategory) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Subcategory);
      }
      if (underlyingCase_ == UnderlyingOneofCase.ItemType) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Criteria other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Kind != global::Tradie.Analyzer.Proto.CriteriaKind.Unknown) {
        Kind = other.Kind;
      }
      switch (other.UnderlyingCase) {
        case UnderlyingOneofCase.Modifier:
          if (Modifier == null) {
            Modifier = new global::Tradie.Analyzer.Proto.Modifier();
          }
          Modifier.MergeFrom(other.Modifier);
          break;
        case UnderlyingOneofCase.League:
          if (League == null) {
            League = new global::Tradie.Analyzer.Proto.League();
          }
          League.MergeFrom(other.League);
          break;
        case UnderlyingOneofCase.Category:
          Category = other.Category;
          break;
        case UnderlyingOneofCase.Subcategory:
          Subcategory = other.Subcategory;
          break;
        case UnderlyingOneofCase.ItemType:
          if (ItemType == null) {
            ItemType = new global::Tradie.Analyzer.Proto.ItemType();
          }
          ItemType.MergeFrom(other.ItemType);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Kind = (global::Tradie.Analyzer.Proto.CriteriaKind) input.ReadEnum();
            break;
          }
          case 82: {
            global::Tradie.Analyzer.Proto.Modifier subBuilder = new global::Tradie.Analyzer.Proto.Modifier();
            if (underlyingCase_ == UnderlyingOneofCase.Modifier) {
              subBuilder.MergeFrom(Modifier);
            }
            input.ReadMessage(subBuilder);
            Modifier = subBuilder;
            break;
          }
          case 90: {
            global::Tradie.Analyzer.Proto.League subBuilder = new global::Tradie.Analyzer.Proto.League();
            if (underlyingCase_ == UnderlyingOneofCase.League) {
              subBuilder.MergeFrom(League);
            }
            input.ReadMessage(subBuilder);
            League = subBuilder;
            break;
          }
          case 98: {
            Category = input.ReadString();
            break;
          }
          case 106: {
            Subcategory = input.ReadString();
            break;
          }
          case 114: {
            global::Tradie.Analyzer.Proto.ItemType subBuilder = new global::Tradie.Analyzer.Proto.ItemType();
            if (underlyingCase_ == UnderlyingOneofCase.ItemType) {
              subBuilder.MergeFrom(ItemType);
            }
            input.ReadMessage(subBuilder);
            ItemType = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Kind = (global::Tradie.Analyzer.Proto.CriteriaKind) input.ReadEnum();
            break;
          }
          case 82: {
            global::Tradie.Analyzer.Proto.Modifier subBuilder = new global::Tradie.Analyzer.Proto.Modifier();
            if (underlyingCase_ == UnderlyingOneofCase.Modifier) {
              subBuilder.MergeFrom(Modifier);
            }
            input.ReadMessage(subBuilder);
            Modifier = subBuilder;
            break;
          }
          case 90: {
            global::Tradie.Analyzer.Proto.League subBuilder = new global::Tradie.Analyzer.Proto.League();
            if (underlyingCase_ == UnderlyingOneofCase.League) {
              subBuilder.MergeFrom(League);
            }
            input.ReadMessage(subBuilder);
            League = subBuilder;
            break;
          }
          case 98: {
            Category = input.ReadString();
            break;
          }
          case 106: {
            Subcategory = input.ReadString();
            break;
          }
          case 114: {
            global::Tradie.Analyzer.Proto.ItemType subBuilder = new global::Tradie.Analyzer.Proto.ItemType();
            if (underlyingCase_ == UnderlyingOneofCase.ItemType) {
              subBuilder.MergeFrom(ItemType);
            }
            input.ReadMessage(subBuilder);
            ItemType = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
